---
version: "3.7"

services:
  keycloak-postgres:
    container_name: keycloak-postgres
    image: "postgres:15.4"
    volumes:
        - ./dev-environment/docker-config/postgres/data:/var/lib/postgresql/data:rw
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak
    ports:
        - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: postgres-pgadmin
    image: "dpage/pgadmin4:7.8"
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@postgres.dev
        - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
        - "5050:80"
    restart: unless-stopped

  keycloak:
    image: 'bitnami/keycloak:22.0.5'
    container_name: keycloak
    depends_on:
        - "keycloak-postgres" # the name of the service above
    restart: unless-stopped
    ports:
        - '8180:8080' # Changing this port because 8080 is usually the default for the actual app, e.g., Quarkus or Spring
    environment:
        - KEYCLOAK_ADMIN_USER=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KEYCLOAK_DATABASE_NAME=keycloak
        - KEYCLOAK_DATABASE_USER=keycloak
        - KEYCLOAK_DATABASE_PASSWORD=keycloak
        - KEYCLOAK_DATABASE_HOST=keycloak-postgres
