server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/vue-keycloak-auth
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allowed-origins: "*"